### ISSUE TITLE
Unreacheable MQTT server results in silent wait with no message.

### ISSUE THREAD

**Issue by jflamy** [nemikor-solutions/blue-owl-core#17]
If a wrong MQTT server address is given, the program appears to sit there silently.
The default timeout is 30 seconds, but no message is given.
Needs a more reasonable timeout + error message on timeout reached.

See proposed fix in fork: https://github.com/owlcms/blue-owl/commit/123b78c1d192f165b553e5cc5ddf110691594c09

**Comment by scottgonzalez** [comment]
This dies pretty quickly with an appropriate error for me:

```
> cross-env DEBUG=blue-owl:* ts-node -r tsconfig-paths/register "./src/scripts/referee.ts"

  blue-owl:owlcms client error +0ms
Error: connect ECONNREFUSED 127.0.0.1:1883
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16) {
  errno: -61,
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 1883
}
```
