### ISSUE TITLE
Full kit for federations

### ISSUE THREAD

**Issue by scottgonzalez** [nemikor-solutions/blue-owl-core#2]
Produce a full kit for federations to use.

* Three referees
* Timekeeper
* 3 or 5 person jury
* Support a single computer running Blue Owl with all devices connected via Ethernet.

**Comment by jflamy** [comment]
Continental championships use 3 person jurys.  Running off the countdown, jury and announcer laptops would be acceptable — the main issue is the trouble of having to install and keep Node up to date on the 3 devices.

**Comment by scottgonzalez** [comment]
Building an [Electron app](https://www.electronjs.org/) would at least ease that process.

Another option is to increase the cost and build time by bundling a single-board computer like a Raspberry Pi with each microcontroller. The project scope gets quite a bit bigger, but that would allow us to coordinate everything from one main computer. We can then run web servers and clients directly in Node.js and pass configurations such as the MQTT URL and the platform via custom endpoints. The individual devices could potentially even be remotely upgraded to newer versions from the main computer.

I'll create a separate issue for what we have planned for the first milestone to support the 3 person jury with each device connected directly to a laptop.

**Comment by jflamy** [comment]
Another option would be https://github.com/fivdi/pi-io

**Comment by scottgonzalez** [comment]
A GUI for specific hardware builds is out of scope for this project. Commercial devices will be made available separately.
