### ISSUE TITLE
Reset jury decisions on deliberation and challenge

### ISSUE THREAD

**Issue by scottgonzalez** [nemikor-solutions/blue-owl-core#20]
Requires new MQTT message from owlcms.

**Comment by jflamy** [comment]
New message published by owlcms in version 38.1.0-beta04 [juryDeliberation](https://owlcms.github.io/owlcms4-prerelease/#/MQTTMessages?id=subscribed-by-jury-devices)

**Comment by scottgonzalez** [comment]
Requires new message for challenges: https://github.com/jflamy/owlcms4/issues/680
