### ISSUE TITLE
spurious messages when USB port already used

### ISSUE THREAD

**Issue by jflamy** [nemikor-solutions/blue-owl-core#24]
If another program is already using a serial port (e.g., owlcms-firmata), version 1.1 correctly detects that the port is used,
In the following screen shot, COM9 is already used.  COM5 is the blue-owl device.  Cannot tell if the firmware timeout messages pertain to COM9 or COM5, but both devices work.

![image](https://github.com/scottgonzalez/blue-owl-core/assets/678663/5f165022-7f8a-4342-b4d0-3b40769dc569)

**Comment by scottgonzalez** [comment]
Unfortunately these logs come from Johnny-Five and can't be disabled. However, future versions of the Blue Owl app will be packaged in a way that does not display the full terminal logs and only displays the Blue Owl logs, so these messages will not be displayed (there will be a true native application that does not run a script in the terminal and does not open a web browser).

`blue-owl-core` will continue to display these logs in the terminal, at least as long as is remains built on top of Johnny-Five. I would like to eventually build this directly on top of `firmata.js`.

**Comment by scottgonzalez** [comment]
Closing as the issue in Blue Owl is resolved. `blue-owl-core` will continue to display these messages.
