### ISSUE TITLE
Support MQTT authentication

### ISSUE THREAD

**Issue by scottgonzalez** [nemikor-solutions/blue-owl-core#8]
`Owlcms` should support connecting to authenticated MQTT servers.

**Comment by jflamy** [comment]
Had me confused for a second - you meant the blue-owl owlcms façade !

**Comment by scottgonzalez** [comment]
Yup, the `Owlcms` class in Blue Owl. I had intended to add this when I first started, but by the time I had everything else working, I forgot about it until recently 🤦
