### ISSUE TITLE
Deluxe Referee Scripts

### ISSUE THREAD

**Issue by scottgonzalez** [nemikor-solutions/blue-owl-core#9]
Create scripts for referee devices with full IWF support + additional features:
* `referee-confirmation`: Confirmation LEDs
* `referee-vibration`: Vibration warning
* `referee-deluxe` Confirmation LEDs + vibration warning

**Comment by jflamy** [comment]
Vibration is a good feature to add for summoning as well.

**Comment by scottgonzalez** [comment]
Yeah, the "warning" label above is intended to include decision reminders and summoning. Basically any time the buzzer would be used, the vibration would be used as well.

**Comment by scottgonzalez** [comment]
No additional scripts will be added since there's no need for predefined configurations in the open source module.
